# Generated by Django 5.0.1 on 2024-01-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.IntegerField()),
                ('password_validation', models.IntegerField()),
                ('sign', models.ImageField(upload_to='')),
                ('profile_photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
