# Generated by Django 5.0.1 on 2024-01-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_photo',
            field=models.ImageField(default='', upload_to='user/images'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sign',
            field=models.ImageField(default='', upload_to='user/images'),
        ),
    ]
