# Generated by Django 4.1.13 on 2024-01-27 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_person_profile_photo_alter_person_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=20)),
                ('contract_desc', models.TextField(max_length=255)),
                ('discount_type', models.CharField(choices=[('Percentage', '%age'), ('Custom Price', 'Custom Price')], max_length=20)),
                ('per_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_name', models.CharField(max_length=20)),
                ('doctor_email', models.EmailField(default='NONE', max_length=30)),
                ('d_phone', models.BigIntegerField()),
                ('commission', models.IntegerField()),
                ('d_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_photo',
            field=models.ImageField(default='', upload_to='user/images/user'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_name',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('nationality', models.CharField(default='Indian', max_length=20)),
                ('national_id', models.PositiveBigIntegerField()),
                ('p_email', models.EmailField(max_length=30)),
                ('phone_no', models.BigIntegerField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateTimeField()),
                ('age', models.IntegerField(max_length=10)),
                ('age_type', models.CharField(choices=[('Year', 'Year'), ('Month', 'Month'), ('Days', 'Days')], max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('patient_photo', models.ImageField(default='', upload_to='user/images/patient')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.contracts')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.contracts')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.person')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.patient')),
            ],
        ),
    ]
