# Generated by Django 4.1.13 on 2024-01-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_patient_age_alter_patient_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='contract',
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.SmallIntegerField(default='0'),
        ),
    ]
