# Generated by Django 4.1.13 on 2024-01-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_patient_contract_alter_patient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AddField(
            model_name='patient',
            name='Age',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
